# Generated by Django 2.2.7 on 2019-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
