# Generated by Django 2.2.7 on 2019-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='post',
            name='document_type',
            field=models.CharField(choices=[('MD', 'Markdown'), ('NOTEBOOK', 'Jupyter Notebook'), ('RAW', 'Raw Text')], default='RAW', max_length=140),
        ),
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
