# Generated by Django 2.2.7 on 2019-11-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0004_auto_20191128_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
