# Generated by Django 2.2.7 on 2019-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0005_auto_20191128_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=5, max_length=1000),
            preserve_default=False,
        ),
    ]
