# Generated by Django 2.2.7 on 2019-12-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0007_auto_20191201_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document_type',
            field=models.CharField(choices=[('MARKDOWN', 'Markdown'), ('NOTEBOOK', 'Jupyter Notebook'), ('RAW', 'Raw Text')], default='RAW', max_length=140),
        ),
    ]
