# Generated by Django 2.2.7 on 2019-12-17 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0008_auto_20191209_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
