# Generated by Django 2.2.7 on 2019-12-17 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0009_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
